#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist
rm -rf dist/*

for os in $(ls bin); do
  for arch in $(ls bin/$os); do
    pushd bin/$os/$arch
    tar -czf "docker-machine-driver-zstack.tgz" ./docker-machine-driver-zstack*
    popd
    mkdir -p dist/$os/$arch
    mv bin/$os/$arch/docker-machine-driver-zstack.tgz dist/$os/$arch/docker-machine-driver-zstack.tgz
  done
done
